service:
  model:
    format: "torchscript"
    path: "data/models/model.ts.pt"
  input:
    channels: 3
    height: 32
    width: 32
    encoding: "flat"
  labels:
    - airplane
    - automobile
    - bird
    - cat
    - deer
    - dog
    - frog
    - horse
    - ship
    - truck
    
